version: '3.5'
services:
  movabletype:
    build : .
    container_name: mt
    restart: always
    ports:
      - 80:80
    depends_on:
      - mysql
      - memcached
    environment:
      TZ: Asia/Tokyo
    volumes:
      - ./:/var/www/html
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      TZ: Asia/Tokyo
      MYSQL_ROOT_PASSWORD: 'P@ssw0rd'
      MYSQL_DATABASE: movabletype
      MYSQL_USER: movabletype
      MYSQL_PASSWORD: movabletype
    volumes:
      - mysql-data:/var/lib/mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
  memcached:
    image: memcached
    container_name: memcached
    restart: always
    ports:
      - 11211:11211
volumes:
  mysql-data:
    name: mysql
